version: "3.4"
networks:
  monitor:
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    hostname: elasticsearch
    privileged: true
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - "${PWD}/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "${PWD}/elasticsearch/data:/usr/share/elasticsearch/data"
      - "${PWD}/elasticsearch/logs:/usr/share/elasticsearch/logs"
    environment:
      - TZ=Asia/Shanghai
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    networks:
      - monitor

  oap:
    image: apache/skywalking-oap-server:9.2.0
    container_name: oap
    hostname: oap
    restart: always
    ports:
      - "11800:11800"
      - "12800:12800"
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - TZ=Asia/Shanghai
      - SW_STORAGE=elasticsearch
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
    networks:
      - monitor
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  oap-ui:
    image: apache/skywalking-ui:9.2.0
    container_name: oap-ui
    hostname: oap-ui
    restart: always
    privileged: true
    ports:
      - "8090:8080"
    environment:
      - TZ=Asia/Shanghai
      - SW_OAP_ADDRESS=http://oap:12800
    networks:
      - monitor
    depends_on:
      - elasticsearch
      - oap
    links:
      - oap