version: '3'
networks:
  monitor:
    driver: bridge

services:
  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"  #设置使用jvm内存大小
      - TZ=Asia/Shanghai
    volumes:
      - $PWD/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - $PWD/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - $PWD/data:/usr/share/elasticsearch/data
      - $PWD/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - monitor
    deploy:
      replicas: 2
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.14.0
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200"
      - TZ=Asia/Shanghai
    volumes:
      - $PWD/kibana.yml:/usr/share/kibana/config/kibana.yml #挂载logstash的配置文件
    ports:
      - 5601:5601
    networks:
      - monitor


  logstash:
    image: logstash:7.14.0
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - $PWD/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es
    ports:
      - 4560:4560
    networks:
      - monitor

  filebeat:
    image: elastic/filebeat:7.14.0
    container_name: filebeat
    volumes:
      - $PWD/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /home/logs:/home/logs/
      - /var/log//log4j:/var/log/log4j/
    depends_on:
      - logstash
    networks:
      - monitor